services:
  # Backend Service
  - type: web
    name: crypto-intelligence-api
    env: docker
    dockerfile: backend/Dockerfile.prod
    rootDir: .
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: crypto-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256

  # Database
databases:
  - name: crypto-db
    plan: free
